### ISSUE TITLE
Allow axios options to be overriden

### ISSUE THREAD

**Issue by OmgImAlexis** [0xflotus/jsonbox-node#5]
I've got a custom jsonbox server that's has a `100MB` limit on the body instead of the normal `10KB`.

Could you please allow axios's config object to be updated or set the default to `Infinity` since the jsonbox server will limit the body with it's validation function.

Ref: https://github.com/axios/axios/issues/1362

**Comment by 0xflotus** [comment]
> I've got a custom jsonbox server that's has a `100MB` limit on the body instead of the normal `10KB`.
> 
> Could you please allow axios's config object to be updated or set the default to `Infinity` since the jsonbox server will limit the body with it's validation function.
> 
> Ref: [axios/axios#1362](https://github.com/axios/axios/issues/1362)

Maybe if you can wait a few days, I will try to implement it, or feel free to create a PR :)

**Comment by 0xflotus** [comment]
> I've got a custom jsonbox server that's has a `100MB` limit on the body instead of the normal `10KB`.
> 
> Could you please allow axios's config object to be updated or set the default to `Infinity` since the jsonbox server will limit the body with it's validation function.
> 
> Ref: [axios/axios#1362](https://github.com/axios/axios/issues/1362)

If you want to use a custom AxiosConfig, you can pass it as last argument.

e.g. 

```javascript
const jb = new JsonBox();
jb.read(BOX_ID, "users", undefined, { maxContentLength: 2000 });
```

**Comment by OmgImAlexis** [comment]
@0xflotus it'd be nice if you would allow the same for the JsonBox class so we can have defaults set for all future requests.

**Comment by 0xflotus** [comment]
> @0xflotus it'd be nice if you would allow the same for the JsonBox class so we can have defaults set for all future requests.

Ok I changed this, now you can pass an AxiosRequestConfig Object in constructor call.

Thanks for this hint. :)
